runtime: python39
entrypoint: uvicorn main:app --host=0.0.0.0 --port=${PORT:-8080}

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

env_variables:
  VARIABLE_NAME: "value"
